### ISSUE TITLE
Add Monastery Mentor

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/cube#1]
![Monastery Mentor](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=391883&type=card)

I think this would be a good card to add to the cube. There are plenty of great spells to trigger it and it's shown up in Legacy decks quite a bit recently.

**Comment by davidchambers** [comment]
:+1:

**Comment by maxcountryman** [comment]
![Precinct Captain](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=270792&type=card)

Maybe cutting Precinct Captain makes the most sense?

**Comment by davidchambers** [comment]
Works for me. My view is that cards with a mana cost of `{W}{W}` hurt the draft, as they're only playable in predominantly white decks, and are thus less keenly contested. (The same applies to `{U}{U}`, `{B}{B}`, `{R}{R}`, and `{G}{G}`, of course.)

**Comment by maxcountryman** [comment]
Agree. My thinking here also is that Mentor has a similar (albeit much more powerful) effect so White isn't losing anything in the process.

**Comment by davidchambers** [comment]
In addition to having a mana cost which more decks can accommodate, Mentor has the advantage of being good in both aggressive and controlling decks.
