### ISSUE TITLE
Add Tasigur, the Golden Fang

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/cube#2]
![Tasigur, the Golden Fang](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=391937&type=card)

I think this would be a good addition to Black: It makes the color more appealing but doesn't require committing to mono Black. I don't necessarily know what to cut for it though.

**Comment by davidchambers** [comment]
This cycle of cards is terrific in cube. I dislike two-colour cards (and strongly dislike three-colour cards) because they're so narrow, but Tasigur could be played in mono black, UB, BG, UBG, or five-colour.

**Comment by maxcountryman** [comment]
Absolutely. Perhaps it's worth considering we cut Massacre Wurm or Phyrexian Obliterator for Tasigur?

![Massacre Wurm](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=214044&type=card)

![Phyrexian Obliterator](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=214386&type=card)

**Comment by maxcountryman** [comment]
Gatekeeper of Malakir is another card that could probably be cut in favor of less {B} intensive cards. 

![Gatekeeper of Malakir](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=368479&type=card)

**Comment by davidchambers** [comment]
I would cut either the `{B}{B}{B}{B}` or the `{B}{B}({B})` in a heartbeat.
