### ISSUE TITLE
Viability of the new dual lands?

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/cube#3]
I'm wondering if the new dual land cycle will be a good cube candidate for addition to the cube? (Perhaps instead of the pain lands?) Certainly at this time it probably is not given we only have half the cycle. But assuming we end up with the full set of ten, would more fetch targets be good for the cube?

**Comment by davidchambers** [comment]
Pain lands are only _very_ good in two-colour decks. I prefer temples and single-colour lands with abilities (e.g. Treetop Village), as they can be played in single-colour decks too.

**Comment by maxcountryman** [comment]
That makes sense. Given the new lands are fetchable, I'm inclined to replace the pain lands with them--my thinking here is as you said, pain lands aren't particularly amazing in decks of more than two colors and we have all the fetch lands. The downside is we already have twenty fetch targets. So maybe more targets is not beneficial. The lands also aren't free of downside: they come into play tapped if you don't control two or more basic lands.

**Comment by maxcountryman** [comment]
I think for the time being these won't make the cut.
