### ISSUE TITLE
Add Jace, Vryn's Prodigy

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/cube#4]
![Jace, Vryn's Prodigy](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=398434&type=card)

![Jace, Telepath Unbound](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=398435&type=card)

This is my favorite card from Origins: It's a combination of Merfolk Looter and Snapcaster Mage (with the added upside that Jace does not give the card Flaskback and as such it can be cast for alternate costs). This card is just such good value, all the way around.

**Comment by davidchambers** [comment]
:thumbsup:

**Comment by maxcountryman** [comment]
Maybe cut Enclave Cryptologist for it? Blue is always so difficult to cut.

**Comment by davidchambers** [comment]
Sounds like an upgrade to me. :)
